# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1548268784);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1548181582);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1548181822);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1548181702);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 235520);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1548616416787");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1548620016787");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1548616410");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20161130223840");
user_pref("browser.startup.homepage_override.mstone", "45.5.1");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1548267860602");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1548181540943");
user_pref("datareporting.policy.firstRunTime", "1548181460595");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 31016);
user_pref("datareporting.sessions.current.main", 1842);
user_pref("datareporting.sessions.current.sessionRestored", 30772);
user_pref("datareporting.sessions.current.startTime", "1548616379711");
user_pref("datareporting.sessions.current.totalTime", 15);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1548181450454,\"a\":2,\"t\":57,\"c\":false,\"m\":2139,\"fp\":31037,\"sr\":30581}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1548204594970,\"a\":1,\"t\":55,\"c\":false,\"m\":1960,\"fp\":28283,\"sr\":27827}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1548254488162,\"a\":0,\"t\":17,\"c\":false,\"m\":1884,\"fp\":26615,\"sr\":26089}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1548268646747,\"a\":0,\"t\":25,\"c\":false,\"m\":2068,\"fp\":51053,\"sr\":59300}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.5.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1548268785);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.5.1");
user_pref("extensions.lastPlatformVersion", "45.5.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1480581486000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.5.1\",\"st\":1480581484000}}}");
user_pref("gecko.buildID", "20161130223840");
user_pref("gecko.mstone", "45.5.1");
user_pref("idle.lastDailyNotification", 1548616460);
user_pref("media.gmp-manager.buildID", "20161130223840");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 12892);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1548616381);
user_pref("toolkit.telemetry.cachedClientID", "1129e1b4-214a-49e5-bf0b-e6b09a5fee58");
user_pref("toolkit.telemetry.previousBuildID", "20161130223840");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
